version: '3.6'

services:
    sqlserver:
        image: 'mcr.microsoft.com/mssql/server:2019-latest'
        container_name: 'sqlserver'
        ports: 
            - '1434:1433'
        environment:
            SA_PASSWORD: 'STr0ng!p@s5w0rd'
            ACCEPT_EULA: 'Y'

    mongodev:
        image: 'mongo:latest'
        container_name: mongodev
        ports:
            - '27018:27017'

    rabbitmq:
        image: masstransit/rabbitmq
        container_name: 'rabbitmq'
        ports: [
            15672:15672,
            5672:5672       
        ]

    zookeeper:
        image: confluentinc/cp-zookeeper:5.5.1
        hostname: zookeeper
        container_name: zookeeper
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000

    broker:
        image: confluentinc/cp-kafka:5.5.1
        hostname: broker
        container_name: broker
        depends_on:
            - zookeeper
        ports:
            - "29092:29092"
            - "9092:9092"
            - "9101:9101"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_JMX_PORT: 9101

    kafka_manager:
        image: hlebalbau/kafka-manager:stable
        depends_on:
            - zookeeper
        ports:
            - "9000:9000"
        environment:
            ZK_HOSTS: "zookeeper:2181"
            APPLICATION_SECRET: "random-secret"